//
//  CustomBackButton.swift
//  Trivia
//
//  Created by Chris Lucas on 07.09.20.
//  Copyright © 2020 HEIA-FR INFO. All rights reserved.
//

import Foundation
import UIKit

//
// func : getCustomBackButton(title: String) -> UIButton
//
// Description : Create a custom back button while keeping almost the same design as the default one generated by the navigation component.
//
// Usage : self.navigationItem.leftBarButtonItem = UIBarButtonItem(customView: getCustomBackButton(title: Back) (do not forget to add a target for the click event
//
func getCustomBackButton(title: String) -> UIButton {
    let backButton = UIButton(type: .system)
    backButton.setImage(UIImage(systemName: "chevron.left", withConfiguration: UIImage.SymbolConfiguration(pointSize: 17, weight: .bold)), for: .normal)
    backButton.setTitle(title, for: .normal)
    backButton.titleLabel?.font = UIFont.systemFont(ofSize: 17)
    backButton.setTitleColor(backButton.tintColor, for: .normal)
    backButton.imageEdgeInsets = UIEdgeInsets(top: 0, left: -14, bottom: 0, right: 0)
    backButton.titleEdgeInsets = UIEdgeInsets(top: 0, left: -8, bottom: 0, right: 0)
    return backButton
}
